### ISSUE TITLE
bug report: export command error

### ISSUE THREAD

**Issue by molingyu** [phodal/adr#2]
`adr export csv` and `adr export json` error!

csv:
```shell
adr export CSV
{ Error: ENOENT: no such file or directory, open 'undefined0001-test.md'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at getAllStatus (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/StatusHelper.js:37:23)
    at Object.getLatestStatus (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/StatusHelper.js:56:21)
    at buildFunc (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/output/CSVBuilder.js:13:49)
    at /home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/base/GenerateBuilder.js:23:17
    at Array.forEach (<anonymous>)
    at GenerateBuilder.setBody (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/base/GenerateBuilder.js:15:20)
    at CSVBuilder.buildContent (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/output/CSVBuilder.js:25:14)
    at output (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/output.js:26:26)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'undefined0001-test.md' }
```

json:
```shell
adr -o json
{ Error: ENOENT: no such file or directory, open 'undefined0001-test.md'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at getAllStatus (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/StatusHelper.js:37:23)
    at Object.getLatestStatus (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/StatusHelper.js:56:21)
    at buildFunc (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/output/JSONBuilder.js:12:49)
    at /home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/base/GenerateBuilder.js:23:17
    at Array.forEach (<anonymous>)
    at JsonGenerateBuilder.setBody (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/base/GenerateBuilder.js:15:20)
    at JSONBuilder.buildContent (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/output/JSONBuilder.js:25:14)
    at output (/home/shitake/.nvm/versions/node/v9.3.0/lib/node_modules/adr/build/main/lib/output.js:26:26)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'undefined0001-test.md' 
```

**Comment by phodal** [comment]
@molingyu upgrade to adr@1.0.8
