### ISSUE TITLE
Cannot create new file (Node 16)

### ISSUE THREAD

**Issue by areindl** [phodal/adr#40]
* **I'm submitting a ...**
[ ] language request
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

I just get start with this tool.

I was sending this command on the CLI (I already init the folder - it worked):

`adr new "no need for monorepo" `

This is the error message:

```bash
/Users/anton/.nvm/versions/node/v16.14.1/lib/node_modules/adr/build/main/lib/create.js:35
    console.log(i18n.logSavePath + savePath);
                     ^

TypeError: Cannot read properties of undefined (reading 'logSavePath')
    at create (/Users/anton/.nvm/versions/node/v16.14.1/lib/node_modules/adr/build/main/lib/create.js:35:22)
    at /Users/anton/.nvm/versions/node/v16.14.1/lib/node_modules/adr/build/main/cli.js:23:29
    at Array.forEach (<anonymous>)
    at Command.<anonymous> (/Users/anton/.nvm/versions/node/v16.14.1/lib/node_modules/adr/build/main/cli.js:23:12)
    at Command.listener [as _actionHandler] (/Users/anton/.nvm/versions/node/v16.14.1/lib/node_modules/adr/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/Users/anton/.nvm/versions/node/v16.14.1/lib/node_modules/adr/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/Users/anton/.nvm/versions/node/v16.14.1/lib/node_modules/adr/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/Users/anton/.nvm/versions/node/v16.14.1/lib/node_modules/adr/node_modules/commander/index.js:882:12)
    at Command.parse (/Users/anton/.nvm/versions/node/v16.14.1/lib/node_modules/adr/node_modules/commander/index.js:717:10)
    at Object.<anonymous> (/Users/anton/.nvm/versions/node/v16.14.1/lib/node_modules/adr/build/main/cli.js:78:9)

```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Any idea? Am I doing it wrong?

**Comment by phodal** [comment]
It seems it's a language issues? Could you share you `.adr.json` ? like:

```json
{"language":"en","path":"docs/adr/","prefix":"","digits":4}
```

**Comment by areindl** [comment]
@phodal thanks! you are right. I changed the config to `en` and it worked. I had it set to `en-us`. 

Maybe this should be added to the docs. 

Thanks for your help!

**Comment by phodal** [comment]
Sorry for it, maybe we need to follow the standard i18n spec.
